remote_theme: pages-themes/cayman@v0.2.0

title: 'AWS Cloud Practitioner Short Notes'
description: 'If you are preparing for AWS Cloud Practitioner Exam, this guide will help you with quick revision before the exam. I share the notes I used to study and pass exam.'
show_downloads: false

github:
  repository_url: '/index.html'
  owner_url: "https://nirav-kanani.netlify.app/"